apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-cm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-rs-cm
  template:
    metadata:
      labels:
        app: myapp-rs-cm
    spec:
      containers:
      - name: myapp-rs-cm
        image: ghcr.io/c1t1d0s7/go-myweb:alpine
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: myapp-message
              key: message
        args:
        - $(MESSAGE)

