apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-headless
  labels:
    app: myapp-svc-headless
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  clusterIP: None
  selector:
    app: myapp-sts
