apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-env
spec:
  containers:
  - name: myapp
    image: c1t1d0s7/myweb
    ports:
    - containerPort: 8080
    env:
    - name: MESSAGE
      value: "Customized Hello World"
