apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-pod-https
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-https
  template:
    metadata:
      labels:
        app: nginx-https
    spec:
      containers:
      - image: nginx
        name: nginx-https
        volumeMounts:
        - name: nginx-tls-config
          mountPath: /etc/nginx/conf.d
        - name: https-cert
          mountPath: /etc/nginx/ssl
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 433
          protocol: TCP
      volumes:
      - name: nginx-tls-config
        configMap:
          name: nginx-tls-config
      - name: https-cert
        secret:
          secretName: nginx-tls-secret
